server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3307/user_management_db?allowPublicKeyRetrieval=true&sslMode=DISABLED&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    test:
      url: jdbc:h2:mem/unit_test_db
      driver-class-name: org.h2.Driver
      username: sa
      password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: user-management-service
  kafka:
    producer:
      bootstrap-servers: host.docker.internal:9092 # kafka name in docker service

eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka

application:
  security:
    jwt:
      secret-key: personalFinanceTrackerKeyA4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f
      expiration: 86400000

