spring:
  profiles:
    active: cloud
  application:
    name: user-management-service

server:
  port: 8081


application:
  security:
    jwt:
      secret-key: personalFinanceTrackerKeyA4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f
      expiration: 86400000